Release sage 2.0.0 torsion
openforcefield/qca-dataset-submission pull request #419
Opened 2024-12-18 20:07 UTC by jaclark5

## New Submission Checklist

- [X] Created a new folder in the submissions directory containing the dataset
- [X] Added `README.md` describing the dataset see [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2020-03-26-OpenFF-Gen-2-Torsion-Set-6-supplemental-2) for examples
- [X] All files used to produce the dataset are included with a description
- [X] Dataset follows the QCSubmit schema defined for [Datasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L340), [OptimizationDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1062) and [TorsionDriveDatasets](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L1225)
- [X] Dataset filename matches pattern `dataset*.json`; may feature a compression extension, such as `.bz2`
- [X] A PDF depicting the molecules is attached, in the case of torsiondrives this should include the highlighting of the central bond, this can be done automatically using [qcsubmit](https://github.com/openforcefield/qcsubmit/blob/56680a7d3298b5d8962edcb840b0fdb34558c053/qcsubmit/datasets.py#L854). 
- [ ] QCSubmit validation passed
- [ ] Made a new dataset entry in the mapping table in repository `README.md`
- [ ] Ready to submit!

2024-12-19 04:08 UTC, lilyminium requested changes
Largely LGTM, just a few minor nitpicks!

2024-12-19 04:08 UTC, lilyminium commented on submissions/2024-12-17-OpenFF-Sage-2.0.0-Torsion-Drive-Training-Dataset-v1.0/ds_info.json
> +    "description": "A quantum chemical (QC) dataset curated to train the OpenFF 2.0.0 Sage torsion potentials. This QC dataset with the OpenFF default level of theory, B3LYP-D3BJ/DZVP, is used to ben
```suggestion
    "description": "A quantum chemical (QC) dataset curated to train the OpenFF 2.0.0 Sage torsion potentials. This QC dataset with the OpenFF default level of theory, B3LYP-D3BJ/DZVP, is used to benchmark Sage geometries and energetics. These optimized conformer geometries were used to train one dimensional torsional profiles. This Generation 2 dataset increases chemical diversity when compared to Generation 1, which are of value to our industry partners. Large molecules (>20 heavy atoms) were also included, including more flexible molecules and a greater degree of conformational variation which provide intramolecular interactions. This is the complete TorsionDrive dataset used for training OpenFF 2.0.0 Sage, consisting of the following datasets: 'OpenFF Gen 2 Torsion Set 1 Roche', 'OpenFF Gen 2 Torsion Set 2 Coverage', 'OpenFF Gen 2 Torsion Set 3 Pfizer Discrepancy', 'OpenFF Gen 2 Torsion Set 4 eMolecules  - Discrepancy', 'OpenFF Gen 2 Torsion Set 5 Bayer' and 'OpenFF Gen 2 Torsion Set 6 supplemental 2'. The `HydrogenBondFilter(method='baker-hubbard')` filter was applied, and the following record IDs were dropped due to issues with ForceBalance: 6098580, 2703504, 2703505, 18045478. Further information can be found in the curation scripts for the linked repositories.",
```

Some typos and suggestions.

2025-04-29 16:00 UTC, jaclark5 commented
@lilyminium Because of how this works, I can't generate the statistics until I make the dataset. If everything that is here now looks good then I'll run this before merging so that if I need any tweaks I can record them without a PR.

2025-04-30 20:36 UTC, lilyminium commented
To do (from live discussion):
- I'll check the metadata
- JC runs the code once approved
- JC will merge the PR after checking results

2025-04-30 22:09 UTC, lilyminium approved these changes
Largely LGTM Jen, I added some nitpicky comments to the description and the version number should be updated :-)

2025-04-30 22:09 UTC, lilyminium commented on submissions/2025-02-10-OpenFF-Sage-2.0.0-Optimization-Training-Dataset-v1.1/README.md
> +# OpenFF Sage 2.0.0 Training Optimization v1.0
The v1.0 here and v1.1 in the directory name and ds_info.json don't match -- could you please update?

2025-04-30 22:09 UTC, lilyminium commented on submissions/2025-02-10-OpenFF-Sage-2.0.0-Optimization-Training-Dataset-v1.1/README.md
> +A quantum chemical (QC) dataset curated to train [OpenFF 2.0.0 Sage](https://github.com/openforcefield/openff-sage) forcefield, with reparametrized Lennard-Jones (LJ) and valence parameters, the latt
```suggestion
A quantum chemical (QC) dataset curated to train [OpenFF 2.0.0 Sage](https://github.com/openforcefield/openff-sage) forcefield, with reparametrized Lennard-Jones (LJ) and valence parameters, the latter relevant to this dataset. This QC dataset with the OpenFF default level of theory, B3LYP-D3BJ/DZVP, is used to train Sage parameters. These optimized conformer geometries were used in conjunction with the QC dataset used to train one dimensional torsional profiles. This Generation 2 dataset increases chemical diversity when compared to Generation 1, which are of value to our industry partners. Large molecules (>20 heavy atoms) were also included, including more flexible molecules and a greater degree of conformational variation which provide intramolecular interactions.
```

2025-04-30 22:09 UTC, lilyminium commented on submissions/2025-02-10-OpenFF-Sage-2.0.0-Optimization-Training-Dataset-v1.1/README.md
> +This is the complete optimization dataset used for training OpenFF 2.0.0 Sage, consisting of the following datasets:
```suggestion
This is the complete optimization dataset used for training OpenFF 2.0.0 Sage, consisting of molecules from following datasets:
```

2025-04-30 22:09 UTC, lilyminium commented on submissions/2025-02-10-OpenFF-Sage-2.0.0-Optimization-Training-Dataset-v1.1/README.md
> +- Name: OpenFF Sage 2.0.0 Training Optimization Dataset v1.0
Here as well name doesn't match

2025-04-30 22:09 UTC, lilyminium commented on submissions/2025-02-10-OpenFF-Sage-2.0.0-Optimization-Training-Dataset-v1.1/ds_info.json
> +    "description": "A quantum chemical (QC) dataset curated to train the OpenFF 2.0.0 Sage, with reparametrized Lennard-Jones (LJ) and valence parameters, the latter relevant to this dataset. This QC
```suggestion
    "description": "A quantum chemical (QC) dataset curated to train the OpenFF 2.0.0 Sage, with reparametrized Lennard-Jones (LJ) and valence parameters, the latter relevant to this dataset. This QC dataset with the OpenFF default level of theory, B3LYP-D3BJ/DZVP, is used to train Sage parameters. These optimized conformer geometries were used in conjunction with the QC dataset used to train one dimensional torsional profiles. This Generation 2 dataset increases chemical diversity when compared to Generation 1, which are of value to our industry partners. Large molecules (>20 heavy atoms) were also included, offering more flexible molecules and a greater degree of conformational variation which provide intramolecular interactions. This is the complete Optimization dataset used for training OpenFF 2.0.0 Sage, consisting of the following datasets: OpenFF Gen 2 Opt Set 1 Roche', 'OpenFF Gen 2 Opt Set 2 Coverage', 'OpenFF Gen 2 Opt Set 3 Pfizer Discrepancy', 'OpenFF Gen 2 Opt Set 4 eMolecules  - Discrepancy', and 'OpenFF Gen 2 Opt Set 5 Bayer'. The filters were applied: following filters were applied: RecordStatusFilter(status=RecordStatusEnum.complete), ConnectivityFilter(tolerance=1.2), UndefinedStereoFilter(), ConformerRMSDFilter(max_conformers=10), and ElementFilter(allowed_elements=['H', 'C', 'N', 'O', 'S', 'P', 'F', 'Cl', 'Br', 'I']). Further information can be found in the curation scripts for the linked repositories.",
```

2025-04-30 22:09 UTC, lilyminium commented on submissions/2025-02-10-OpenFF-Sage-2.0.0-Torsion-Drive-Training-Dataset-v1.0/README.md
> +geometries where used to train one dimensional torsional profiles. This Generation 2
```suggestion
consists of one dimensional torsional profiles used to train torsion parameters. This Generation 2 
```

2025-04-30 22:09 UTC, lilyminium commented on submissions/2025-02-10-OpenFF-Sage-2.0.0-Torsion-Drive-Training-Dataset-v1.0/README.md
> +used for training OpenFF 2.0.0 Sage, consisting of the following datasets:
```suggestion
used for training OpenFF 2.0.0 Sage, consisting of data drawn from the following datasets: 
```

2025-04-30 22:09 UTC, lilyminium commented on submissions/2025-02-10-OpenFF-Sage-2.0.0-Torsion-Drive-Training-Dataset-v1.0/README.md
> +* Date: 2024-12-17
Update date?

2025-04-30 22:09 UTC, lilyminium commented on submissions/2025-02-10-OpenFF-Sage-2.0.0-Torsion-Drive-Training-Dataset-v1.0/ds_info.json
> +    "description": "A quantum chemical (QC) dataset curated to train the OpenFF 2.0.0 Sage torsion potentials. This QC dataset with the OpenFF default level of theory, B3LYP-D3BJ/DZVP, is used to ben
```suggestion
    "description": "A quantum chemical (QC) dataset curated to train the OpenFF 2.0.0 Sage torsion potentials. This QC dataset with the OpenFF default level of theory, B3LYP-D3BJ/DZVP, consists of one dimensional torsional profiles used to train torsion parameters. This Generation 2 dataset increases chemical diversity when compared to Generation 1, which are of value to our industry partners. Large molecules (>20 heavy atoms) were also included, offering more flexible molecules and a greater degree of conformational variation which provide intramolecular interactions. This is the complete TorsionDrive dataset used for training OpenFF 2.0.0 Sage, consisting of data drawn from the following datasets: 'OpenFF Gen 2 Torsion Set 1 Roche', 'OpenFF Gen 2 Torsion Set 2 Coverage', 'OpenFF Gen 2 Torsion Set 3 Pfizer Discrepancy', 'OpenFF Gen 2 Torsion Set 4 eMolecules  - Discrepancy', 'OpenFF Gen 2 Torsion Set 5 Bayer' and 'OpenFF Gen 2 Torsion Set 6 supplemental 2'. The `HydrogenBondFilter(method='baker-hubbard')` filter was applied, and the following record IDs were dropped due to issues with ForceBalance: 6098580, 2703504, 2703505, 18045478. Further information can be found in the curation scripts for the linked repositories.",
```

2025-05-05 14:45 UTC, lilyminium commented on submissions/2025-02-10-OpenFF-Sage-2.0.0-Torsion-Drive-Training-Dataset-v1.0/ds_info.json
> +    "description": "A quantum chemical (QC) dataset curated to train the OpenFF 2.0.0 Sage torsion potentials. This QC dataset with the OpenFF default level of theory, B3LYP-D3BJ/DZVP, is used to ben
Could you please update this description? The dataset isn't necesssarily used to train 1D profiles but consists of them.

2025-05-05 14:49 UTC, lilyminium commented on submissions/2025-05-01-OpenFF-Sage-2.0.0-Optimization-Training-Dataset-v1.1/README.md
> +- Name: OpenFF Sage 2.0.0 Training Optimization Dataset v1.1
```suggestion
- Name: OpenFF Sage 2.0.0 Optimization Training Dataset v1.1
```
Could you please match the name to the directory? The Training and Optimization are still swapped around

2025-05-20 20:17 UTC, merged